# Generated by Django 3.2.4 on 2024-06-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(default='default', max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('sourceHandle', models.CharField(blank=True, max_length=100, null=True)),
                ('targetHandle', models.CharField(blank=True, max_length=100, null=True)),
                ('animated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(default='default', max_length=100)),
                ('data', models.JSONField()),
                ('position', models.JSONField()),
                ('height', models.IntegerField(default=150)),
                ('width', models.IntegerField(default=150)),
            ],
        ),
    ]
