# Generated by Django 4.2.13 on 2024-06-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('animated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(default='default', max_length=100)),
                ('data', models.JSONField()),
                ('position', models.JSONField()),
            ],
        ),
    ]
