# Generated by Django 4.2.13 on 2024-06-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='enki.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='enki.node'),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('source', 'target')},
        ),
    ]
