# Generated by Django 4.2.13 on 2024-06-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enki', '0003_alter_edge_source_alter_edge_target'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set(),
        ),
    ]
