# Generated by Django 4.2.13 on 2024-06-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enki', '0004_alter_edge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='node',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
