# Generated by Django 3.2.4 on 2024-06-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enki', '0005_node_height_node_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='sourceHandle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='targetHandle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='height',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='node',
            name='width',
            field=models.IntegerField(default=150),
        ),
    ]
