# Generated by Django 4.2.13 on 2024-06-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enki', '0002_alter_edge_source_alter_edge_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='edge',
            name='target',
            field=models.CharField(max_length=100),
        ),
    ]
